[app]
name = "auth_server"
environment = "development"

[client_integrations] # feature flags(middlewares)
allow_logging_middleware = true
allow_request_timeout_middleware = true
allow_rate_limit_middleware = false

[server]
host = "127.0.0.1"
port = 8000
request_timeout_secs = 60

[rate_limit]
enabled = true
requests_per_window = 60
window_secs = 60

[mesh]
enabled = false
url = "http://127.0.0.1:3080"
token = ""
service_name = "auth-service"
service_version = "1.0.0"
advertise_host = ""
heartbeat_interval_secs = 5
external_host = ""
external_scheme = "http"

# [observability]
# enable_tracing = true
# enable_metrics = true
